export {default as Hero} from './home/SliderHero';
export {default as Wedo } from './home/Wedo';
export {default as Testimonial} from './home/Testimonial';
export {default as Brand} from './home/Brand';
export {default as TeamMemb} from './TeamMemb';
export {default as Experiance} from './Experiance';
export {default as Contact} from './Contact';
export {default as Ghead} from './Ghead';
export {default as Gwedo } from './Gwedo';
export {default as Gprod } from './Gprod';