export default{
    name:"about",
    title:"About",
    type:"document",
    fields:[
        {
            name:"slider_image",
            title:"Slider_image",
            type:"array",
            of:[{type:"image"}],
            option:{

            }
        },
        {
            name:"intro",
            title:"Intro",
            type:"string"
        },
        {
            name:"descr",
            title:"Descr",
            type:"string"
        },

        // end of about head // starting our team members

        {
            name:"member",
            title:"Member",
            type:"array",
            of:[
                {
                    name:"name",
                    title:"Name",
                    type:"string"
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                },
                {
                    name:"facebook",
                    title:"Facebook",
                    type:"slug"
                },
                {
                    name:"instagram",
                    title:"Instagram",
                    type:"slug"
                },
                {
                    name:"whatsapp",
                    title:"Whatsapp",
                    type:"slug"
                },
            ]
        },

        //experiance show
        {
            name:"header",
            title:"Header",
            type:"string"
        },
        {
            name:"descr",
            title:"Descr",
            type:"string"
        },
        
        // machine enter
        {
            name:"name",
            title:"Name",
            type:"array",
            of:[
                {
                    name:"name",
                    title:"Name",
                    type:"string"
                },
                {
                    name:"left",
                    title:"Left",
                    type:"image"
                },
                {
                    name:"middle",
                    title:"Middle",
                    type:"image"
                },
                {
                    name:"right",
                    title:"Right",
                    type:"image"
                }
            ]
        },
        {
          name:"office",
          title:"Office",
          type:"array",
          of:[
            {
                name:"image",
                title:"Image",
                type:"image"
            }
          ] 
        }
    ]
}