export default{
    name:"decoration",
    title:"Decoration",
    type:"document",
    fields:[
        {
            name:"slider_image",
            title:"Slider_image",
            type:"array",
            of:[{type:"image"}],
            option:{

            }
        },
        {
            name:"intro",
            title:"Intro",
            type:"string"
        },
        {
            name:"descr",
            title:"Descr",
            type:"string"
        },
        
        //showing the decoration we do
        {
            name:"left",
            title:"Left",
            type:"array",
            of:[
                {
                    name:"dname",
                    title:"Dname",
                    type:"string",
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                }
            ]

        },
        {
            name:"middle",
            title:"Middle",
            type:"array",
            of:[
                {
                    name:"dname",
                    title:"Dname",
                    type:"string",
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                }
            ]

        },
        {
            name:"right",
            title:"right",
            type:"array",
            of:[
                {
                    name:"dname",
                    title:"Dname",
                    type:"string",
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                }
            ]
        }
   ] 
}