export default{
    name:"machine",
    title:"Machine",
    type:"document",
    fields:[
        {
            name:"name",
            title:"Name",
            type:"string"
        },
        {
            name:"left",
            title:"Left",
            type:"image"
        },
        {
            name:"middle",
            title:"Middle",
            type:"image"
        },
        {
            name:"right",
            title:"Right",
            type:"image"
        }
    ]
}