export default{
    name:"printing",
    title:"Printing",
    type:"document",
    fields:[
        {
            name:"header",
            title:"Header",
            type:"string"
        },
        {
            name:"descr",
            title:"Descr",
            type:"block"
        },
        {
            name:"image",
            title:"Image",
            type:"image"
        },

        //body of the printing page
        {
            name:"left",
            title:"Left",
            type:"array",
            of:[
                {
                    name:"dname",
                    title:"Dname",
                    type:"string",
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                }
            ]

        },
        {
            name:"middle",
            title:"Middle",
            type:"array",
            of:[
                {
                    name:"dname",
                    title:"Dname",
                    type:"string",
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                }
            ]

        },
        {
            name:"right",
            title:"right",
            type:"array",
            of:[
                {
                    name:"dname",
                    title:"Dname",
                    type:"string",
                },
                {
                    name:"image",
                    title:"Image",
                    type:"image"
                }
            ]
        }
    ]
}