export default{
    name:"sticker",
    title:"Sticker",
    type:"document",
    fields:[
        {
            name:"name",
            title:"Name",
            type:"string"
        },
        {
            name:"categories",
            title:"Categories",
            type:"reference",
            to:[{type:"scate"}]
        },
        {
            name:"descr",
            title:"Descr",
            type:"string"
        },
        {
            name:"image",
            title:"Image",
            type:"image",
            options:{hotspot: true}
        }
    ]
}